# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               James Ethridge
tagline:             'github.io'
description:         'James Ethridge is a softwae engineer residing in New York, NY.'
url:                 http://jeethridge.github.io/
baseurl:             /
paginate:            5

# About/contact
author:
  name:              James Ethridge
  url:               http://jeethridge.github.io/
  email:             jeethridge@gmail.com

# Custom vars
version:             1.0.0
